theme:
  name: material
  favicon: favicon.ico
  logo: images/safe-logo.png
  palette:
    primary: teal
    scheme: teal
  features:
    - tabs
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/archer2.css

site_name: EPCC SAFE User Documentation
repo_url: https://github.com/EPCCed/safe-docs
repo_name: EPCCed/safe-docs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EPCCed
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/EPCCed

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - "Documentation overview": index.md
  - "SAFE for users": safe-for-users.md
  - "SAFE for PIs and Project Managers": safe-for-managers.md
  - "SAFE for EPCC SHS Research Coordinators": safe-for-shs-rcs.md
  - "Technical Assessments for Project applications": tas.md
  - "Training Course Registrations": training-registrations.md
